### ISSUE TITLE
Broken Links and Different Ports

### ISSUE THREAD

**Issue by jacksonattwood** [ravi0lii/node-sharex-server#4]
Hey there, I have a bit of a problem using this script. All that happens is that it puts a directory in the link so that if I wanted to send a link for this windows capture it sends this: 

http://ftp.nonfatjoker288.com:3854/upload/f/wOpqtkO4.png

But it only works if I remove the `upload` directory from it leaving me with: 

http://ftp.nonfatjoker288.com:3854/f/wOpqtkO4.png

I also can't get the ports to change.

**Comment by ravi0lii** [comment]
Could you please provide your config.json (you can censor your keys but things like the url is important) and the output of the program when you upload a file.
Also, you can change the port by setting a environment varible with the name `SUS_PORT`. If this environment variable isn't set, the script will use the port `3854`.
On Linux, you can use the following command to start the server on port 9000: `SUS_PORT=9000 node app.js`
On Windows, you can use the following command to start the server on port 9000: `set SUS_PORT=9000 && node app.js`

**Comment by jacksonattwood** [comment]
I have fixed the link thing as it was as easy as changing one word in the config file but I'm still having issues with the port as you said to use two commands in one but the terminal (windows powershell) doesn't like double ampersands. I have attached the config anyway. 
[config.txt](https://github.com/Moquo/node-sharex-server/files/1946285/config.txt)

**Comment by ravi0lii** [comment]
In the Windows PowerShell, you can set environment variables with the following syntax: `$env:ENV_VAR_NAME = VALUE`.
We can conclude the following from this: Starting the server on port 9000 is possible with these 2 commands:
```
$env:SUS_PORT = 9000
node app.js
```

**Comment by ravi0lii** [comment]
Is everything working now? Can I close this issue?

**Comment by jacksonattwood** [comment]
Yes you may thanks for the help.
